import React from "react";
import Head from "next/head";
import Footer from "@/components/footer/Footer";
import StreamForm from "@/components/forms/openai/StreamForm";

const StreamMainContent = () => {
  return (
    <>
      <Head>
        <title>OpenAI - Stream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <div className="main-content">
        {/* <DashboardBreadcrumb2 title={"Contact Forms"} /> */}
        <div className="row g-4">
          <StreamForm />
          {/* <ContactForm2/>
            <ContactForm3/>
            <ContactForm4/> */}
        </div>

        <Footer />
      </div>
    </>
  );
};

export default StreamMainContent;
